# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dyu2bN7IlevcPTcu8MP-rx13UmAsRSYW
"""

!pip install easyocr>=1.7.0
!pip install opencv-python-headless>=4.8.0
!pip install gradio>=4.0.0
!pip install python-docx>=0.8.11
!pip install numpy>=1.24.0
!pip install Pillow>=10.0.0
!pip install torch>=2.0.0
!pip install torchvision>=0.15.0

import sys
import subprocess
import os

# Try to import easyocr, if not found, install it
try:
    import easyocr
except ImportError:
    print("📦 Installing easyocr...")
    subprocess.check_call([sys.executable, "-m", "pip", "install", "easyocr", "opencv-python-headless", "gradio", "python-docx", "numpy", "Pillow"])
    import easyocr

import cv2
import numpy as np
import re
import gradio as gr
from PIL import Image
from datetime import datetime
from docx import Document

# ─────────────────────────────────────────────
# OCR MODEL — English + Urdu
# ─────────────────────────────────────────────
print("Loading OCR models...")
try:
    reader = easyocr.Reader(['en', 'ur'], gpu=False, verbose=False)
    print(" OCR models ready!")
except Exception as e:
    print(f" Error loading OCR: {e}")
    print("Trying with just English...")
    reader = easyocr.Reader(['en'], gpu=False, verbose=False)
    print(" English OCR model ready!")

# ─────────────────────────────────────────────
# ADVANCED PREPROCESSING
# ─────────────────────────────────────────────
def preprocess_image(image, mode="auto"):
    """
    Multi-stage preprocessing pipeline.
    mode: 'auto' | 'handwritten' | 'printed' | 'dark'
    """
    img = np.array(image)

    # Handle RGBA
    if len(img.shape) == 3 and img.shape[-1] == 4:
        img = cv2.cvtColor(img, cv2.COLOR_RGBA2RGB)

    # Grayscale
    if len(img.shape) == 3:
        gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
    else:
        gray = img

    # Upscale small images for better OCR
    h, w = gray.shape
    if max(h, w) < 1000:
        scale = 1500 / max(h, w)
        gray = cv2.resize(gray, (int(w * scale), int(h * scale)),
                          interpolation=cv2.INTER_CUBIC)

    try:
        # CLAHE — adaptive contrast
        clahe = cv2.createCLAHE(clipLimit=3.0, tileGridSize=(8, 8))
        enhanced = clahe.apply(gray)
    except:
        enhanced = gray

    if mode == "dark":
        # Invert dark backgrounds
        enhanced = cv2.bitwise_not(enhanced)

    # Denoise
    try:
        denoised = cv2.fastNlMeansDenoising(enhanced, h=10, templateWindowSize=7, searchWindowSize=21)
    except:
        denoised = enhanced

    # Sharpen
    kernel_sharp = np.array([[0, -1, 0], [-1, 5, -1], [0, -1, 0]])
    sharpened = cv2.filter2D(denoised, -1, kernel_sharp)

    # Deskew
    sharpened = deskew(sharpened)

    # Adaptive threshold (best for handwriting + printed)
    try:
        thresh = cv2.adaptiveThreshold(
            sharpened, 255,
            cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
            cv2.THRESH_BINARY,
            31, 10
        )
    except:
        thresh = sharpened

    # Morphological cleanup — remove noise dots
    kernel = np.ones((2, 2), np.uint8)
    cleaned = cv2.morphologyEx(thresh, cv2.MORPH_CLOSE, kernel)

    return cleaned


def deskew(image):
    """Fix tilted/rotated text images."""
    try:
        coords = np.column_stack(np.where(image < 128))
        if len(coords) < 100:
            return image
        angle = cv2.minAreaRect(coords)[-1]
        if angle < -45:
            angle = -(90 + angle)
        else:
            angle = -angle
        if abs(angle) > 30:
            return image  # Too extreme — skip
        (h, w) = image.shape
        M = cv2.getRotationMatrix2D((w // 2, h // 2), angle, 1.0)
        rotated = cv2.warpAffine(
            image, M, (w, h),
            flags=cv2.INTER_CUBIC,
            borderMode=cv2.BORDER_REPLICATE
        )
        return rotated
    except:
        return image


# ─────────────────────────────────────────────
# TEXT CLEANING
# ─────────────────────────────────────────────
def clean_text(text, keep_special=False):
    """Clean extracted text — keep Urdu + English."""
    # Keep: Urdu (0600-06FF), English, digits, punctuation
    if keep_special:
        pattern = r'[^\u0600-\u06FFa-zA-Z0-9\s.,!?:;\-\'\"()\n]'
    else:
        pattern = r'[^\u0600-\u06FFa-zA-Z0-9\s.,!?]'

    text = re.sub(pattern, ' ', text)
    text = re.sub(r'[ \t]+', ' ', text)      # Multiple spaces → single
    text = re.sub(r'\n{3,}', '\n\n', text)   # Triple newlines → double
    return text.strip()


def format_paragraphs(lines):
    """Group lines into paragraphs intelligently."""
    paragraphs = []
    current = []
    for line in lines:
        line = line.strip()
        if not line:
            if current:
                paragraphs.append(' '.join(current))
                current = []
        else:
            current.append(line)
    if current:
        paragraphs.append(' '.join(current))
    return '\n\n'.join(paragraphs)


# ─────────────────────────────────────────────
# MAIN OCR FUNCTION
# ─────────────────────────────────────────────
def convert_handwriting(image, mode, confidence_threshold, output_format):
    if image is None:
        return " Please upload an image first.", None, gr.update(visible=False)

    try:
        start_time = datetime.now()

        # ── PREPROCESSING ──
        processed = preprocess_image(image, mode=mode)

        # ── OCR PASS 1: Preprocessed image ──
        try:
            results1 = reader.readtext(
                processed,
                detail=1,
                paragraph=False,
                contrast_ths=0.1,
                adjust_contrast=0.5,
                text_threshold=0.6,
                low_text=0.3,
                link_threshold=0.3,
            )
        except:
            results1 = []

        # ── OCR PASS 2: Original image (catches what preprocessing may miss) ──
        orig = np.array(image)
        if len(orig.shape) == 3 and orig.shape[-1] == 4:
            orig = cv2.cvtColor(orig, cv2.COLOR_RGBA2RGB)

        try:
            results2 = reader.readtext(
                orig,
                detail=1,
                paragraph=False,
                contrast_ths=0.1,
                adjust_contrast=0.5,
            )
        except:
            results2 = []

        # ── MERGE + DEDUPLICATE ──
        seen_texts = set()
        all_results = []
        threshold = float(confidence_threshold)

        for (bbox, text, prob) in results1 + results2:
            text_clean = text.strip()
            if prob >= threshold and text_clean and text_clean.lower() not in seen_texts:
                seen_texts.add(text_clean.lower())
                all_results.append((bbox, text_clean, prob))

        # Sort by Y position (top to bottom reading order)
        if all_results:
            all_results.sort(key=lambda r: (r[0][0][1] + r[0][2][1]) / 2)

        # ── EXTRACT TEXT ──
        lines = [r[1] for r in all_results]
        raw_text = '\n'.join(lines)
        final_text = clean_text(raw_text, keep_special=True)
        formatted = format_paragraphs(lines)

        if not final_text.strip():
            return (
                " No text detected.\n\n"
                "Tips:\n"
                "• Use a clearer, higher-resolution image\n"
                "• Ensure good lighting — no shadows\n"
                "• Try 'Dark Background' mode if text is light\n"
                "• Make sure text is not too small",
                None,
                gr.update(visible=False)
            )

        # ── STATS ──
        elapsed = (datetime.now() - start_time).total_seconds()
        word_count = len(final_text.split())
        line_count = len([l for l in lines if l.strip()])
        avg_conf = sum(r[2] for r in all_results) / len(all_results) if all_results else 0
        conf_emoji = "" if avg_conf > 0.75 else "" if avg_conf > 0.50 else ""

        stats = (
            f"\n\n{'─'*40}\n"
            f"Stats\n"
            f"  {conf_emoji} Confidence : {avg_conf:.0%}\n"
            f"  Words     : {word_count}\n"
            f"   Lines     : {line_count}\n"
            f"    Time      : {elapsed:.1f}s\n"
            f"{'─'*40}"
        )

        display_text = formatted + stats

        # ── SAVE OUTPUT ──
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        output_path = None

        if output_format == "TXT (.txt)":
            output_path = f"ocr_output_{timestamp}.txt"
            with open(output_path, "w", encoding="utf-8") as f:
                f.write(formatted)

        elif output_format == "Word (.docx)":
            output_path = f"ocr_output_{timestamp}.docx"
            doc = Document()
            doc.add_heading("OCR Extracted Text", 0)
            doc.add_paragraph(f"Date: {datetime.now().strftime('%d %B %Y, %H:%M')}")
            doc.add_paragraph(f"Confidence: {avg_conf:.0%} | Words: {word_count}")
            doc.add_paragraph("─" * 40)
            for para in formatted.split('\n\n'):
                if para.strip():
                    doc.add_paragraph(para.strip())
            doc.save(output_path)

        elif output_format == "Both (.txt + .docx)":
            txt_path = f"ocr_output_{timestamp}.txt"
            docx_path = f"ocr_output_{timestamp}.docx"
            with open(txt_path, "w", encoding="utf-8") as f:
                f.write(formatted)
            doc = Document()
            doc.add_heading("OCR Extracted Text", 0)
            doc.add_paragraph(formatted)
            doc.save(docx_path)
            output_path = docx_path

        return display_text, output_path, gr.update(value=formatted, visible=True)

    except Exception as e:
        return f" Error: {str(e)}\n\nPlease try again with a different image.", None, gr.update(visible=False)


# ─────────────────────────────────────────────
# GRADIO UI
# ─────────────────────────────────────────────
CSS = """
#main-header {
    background: linear-gradient(135deg, #8B3A52, #C4687E, #E8A0B4);
    border-radius: 16px;
    padding: 28px;
    text-align: center;
    color: white;
    margin-bottom: 20px;
    box-shadow: 0 8px 32px rgba(139,58,82,0.3);
}
#main-header h1 { font-size: 1.8rem; margin-bottom: 6px; }
#main-header p  { opacity: 0.85; font-size: 0.95rem; }

.setting-row { background: #FDF0F3; border-radius: 12px; padding: 16px; }
.output-box  { border: 1.5px solid #E8A0B4 !important; border-radius: 12px !important; }

#convert-btn {
    background: linear-gradient(135deg, #C4687E, #8B3A52) !important;
    border: none !important;
    font-size: 1rem !important;
    padding: 14px !important;
    border-radius: 30px !important;
}
#convert-btn:hover { opacity: 0.9; transform: translateY(-1px); }

.tip-box {
    background: #FFF5F7;
    border: 1px solid #F5C6D4;
    border-radius: 12px;
    padding: 16px;
    font-size: 0.85rem;
    color: #8B3A52;
}
"""

with gr.Blocks(css=CSS, title="OCR Pro — Handwriting to Text") as app:

    # ── HEADER ──
    gr.HTML("""
    <div id="main-header">
        <h1> Handwriting to Digital Text</h1>
        <p>Upload any handwritten or printed image → Get accurate text → Download as TXT or Word</p>
        <p style="font-size:0.8rem;margin-top:6px;opacity:0.7;">Supports English + Urdu • Advanced Preprocessing • High Accuracy</p>
    </div>
    """)

    with gr.Row():
        # ── LEFT: INPUT ──
        with gr.Column(scale=1):
            gr.Markdown("### Upload Image")
            image_input = gr.Image(
                type="pil",
                label="Drop image here or click to upload",
                sources=["upload"],
                height=300,
            )

            with gr.Group():
                gr.Markdown("### ⚙️ Settings")
                mode_select = gr.Dropdown(
                    label="Image Type",
                    choices=["auto", "handwritten", "printed", "dark"],
                    value="auto",
                    info="'auto' works for most images"
                )
                conf_slider = gr.Slider(
                    label="Confidence Threshold",
                    minimum=0.1, maximum=0.9, value=0.4, step=0.05,
                    info="Lower = more text detected (may include errors)"
                )
                format_select = gr.Dropdown(
                    label="Output Format",
                    choices=["TXT (.txt)", "Word (.docx)", "Both (.txt + .docx)"],
                    value="Word (.docx)",
                )

            convert_btn = gr.Button(
                " Convert to Digital Text",
                variant="primary",
                elem_id="convert-btn",
                size="lg"
            )

            gr.HTML("""
            <div class="tip-box">
            <b> Tips for best results:</b><br>
            • Flat image, no crumples<br>
            • Good lighting, no shadows<br>
            • Min 300 DPI / high resolution<br>
            • Plain background preferred<br>
            • Use 'dark' mode for light text on dark paper
            </div>
            """)

        # ── RIGHT: OUTPUT ──
        with gr.Column(scale=1):
            gr.Markdown("###  Extracted Text")

            text_output = gr.Textbox(
                label="Result",
                lines=14,
                show_copy_button=True,
                elem_classes=["output-box"],
                placeholder="Extracted text will appear here after conversion...",
            )

            editable_output = gr.Textbox(
                label=" Edit Text (before downloading)",
                lines=8,
                show_copy_button=True,
                visible=False,
                placeholder="You can edit the text here before downloading...",
            )

            file_output = gr.File(
                label="⬇️ Download File",
                visible=False,
            )

            with gr.Row(visible=True):
                clear_btn = gr.Button(" Clear", variant="secondary")

    # ── EXAMPLES ──
    gr.Markdown("---")
    gr.Markdown("### How to Use")
    gr.HTML("""
    <div style="display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-top:8px;">
      <div style="background:#FDF0F3;border:1px solid #F5C6D4;border-radius:12px;padding:20px;text-align:center;">
        <div style="font-size:2rem;margin-bottom:8px;">1️⃣</div>
        <b>Upload</b><br><small>Select your handwritten or printed image</small>
      </div>
      <div style="background:#FDF0F3;border:1px solid #F5C6D4;border-radius:12px;padding:20px;text-align:center;">
        <div style="font-size:2rem;margin-bottom:8px;">2️⃣</div>
        <b>Convert</b><br><small>Click the Convert button — wait 10-30 seconds</small>
      </div>
      <div style="background:#FDF0F3;border:1px solid #F5C6D4;border-radius:12px;padding:20px;text-align:center;">
        <div style="font-size:2rem;margin-bottom:8px;">3️⃣</div>
        <b>Download</b><br><small>Edit if needed, then download TXT or Word file</small>
      </div>
    </div>
    """)

    # ── EVENTS ──
    convert_btn.click(
        fn=convert_handwriting,
        inputs=[image_input, mode_select, conf_slider, format_select],
        outputs=[text_output, file_output, editable_output],
    )

    clear_btn.click(
        fn=lambda: (None, "", None, gr.update(visible=False)),
        outputs=[image_input, text_output, file_output, editable_output],
    )

# ─────────────────────────────────────────────
# LAUNCH
# ─────────────────────────────────────────────
if __name__ == "__main__":
    app.launch(
        share=True,
        debug=False,
        show_error=True,
    )